"""modifying field name full_name to fullname

Revision ID: 7d469a13c016
Revises: b2c73e2d2d7d
Create Date: 2024-04-04 19:32:10.537568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d469a13c016"
down_revision: Union[str, None] = "b2c73e2d2d7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("fullname", sa.String(length=50), nullable=False)
    )
    op.drop_column("clients", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column(
            "full_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("clients", "fullname")
    # ### end Alembic commands ###
