"""updating user model to use role as property rather than a relationship

Revision ID: df9d296887d0
Revises: 09d667f17658
Create Date: 2024-04-04 11:58:00.670716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df9d296887d0"
down_revision: Union[str, None] = "09d667f17658"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("_role_id", sa.Integer(), nullable=False))
    op.drop_constraint("users_role_id_fkey", "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "roles", ["_role_id"], ["id"])
    op.drop_column("users", "role_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("role_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key("users_role_id_fkey", "users", "roles", ["role_id"], ["id"])
    op.drop_column("users", "_role_id")
    # ### end Alembic commands ###
